env:
  GOOS: linux
  BUILD: 0.8.0-beta

functions:
  - name: build
    run:
      - echo ${BUILD}
      - go build --ldflags="-X 'github.com/dcgsteve/secrets/cmd.Version=${BUILD}' -X 'github.com/dcgsteve/secrets/cmd.EncryptionKey=${SECRETS_LIVE_KEY}'" -o bin/${GOOS}/secrets

  - name: build-linux
    env:
      GOOS: linux
    run:
      - $(build)

  - name: build-mac
    env:
      GOOS: darwin
    run:
      - $(build)
