env:
  CGO_ENABLED: 0
  GOOS: linux
  BUILD: 0.9-beta

functions:
  - name: release
    description: build all releases for production
    run:
      - $(build-linux)
      - $(build-mac)
      - $(build-windows)
      - gh release create --generate-notes -t "${BUILD}" ${BUILD} 'bin/secrets' 'bin/secrets-mac' 'bin/secrets.exe'

  - name: prerelease
    description: build all prereleases for production
    run:
      - $(build-linux)
      - $(build-mac)
      - $(build-windows)
      - gh release create --prerelease --generate-notes -t "${BUILD}" ${BUILD} 'bin/secrets' 'bin/secrets-mac' 'bin/secrets.exe'

  - name: build-linux
    env:
      GOOS: linux
      GOARCH: amd64
    run:
      - garble -literals -tiny build --ldflags="-X 'github.com/dcgsteve/secrets/cmd.Version=${BUILD}' -X 'github.com/dcgsteve/secrets/cmd.EncryptionKey=${SECRETS_LIVE_KEY}'" -o bin/secrets

  - name: build-mac
    env:
      GOOS: darwin
      GOARCH: amd64
    run:
      - garble -literals -tiny build --ldflags="-X 'github.com/dcgsteve/secrets/cmd.Version=${BUILD}' -X 'github.com/dcgsteve/secrets/cmd.EncryptionKey=${SECRETS_LIVE_KEY}'" -o bin/secrets-mac

  - name: build-windows
    env:
      GOOS: windows
      GOARCH: 386
    run:
      - garble -literals -tiny build --ldflags="-X 'github.com/dcgsteve/secrets/cmd.Version=${BUILD}' -X 'github.com/dcgsteve/secrets/cmd.EncryptionKey=${SECRETS_LIVE_KEY}'" -o bin/secrets.exe

  - name: install-garble
    description: install Garble (used for production releases)
    run:
      - go install mvdan.cc/garble@latest

  - name: install-gh
    description: install GitHub command line (used for production releases)
    run:
      - bash -c ./install-gh.sh