env:
  CGO_ENABLED: 0
  GOOS: linux
  BUILD: 0.9.4-beta
  IMG_LINUX: secrets-linux-amd64
  IMG_MAC: secrets-mac-arm64
  IMG_WINDOWS: secrets-win-amd64.exe

functions:
  - name: release
    description: build all releases for production
    run:
      - $(build-linux)
      - $(build-mac)
      - $(build-windows)
      - gh release create --generate-notes -t "${BUILD}" ${BUILD} 'bin/${IMG_LINUX}' 'bin/${IMG_MAC}' 'bin/${IMG_WINDOWS}'

  - name: prerelease
    description: build all prereleases for production
    run:
      - $(build-linux)
      - $(build-mac)
      - $(build-windows)
      - gh release create --prerelease --generate-notes -t "${BUILD}" ${BUILD} 'bin/${IMG_LINUX}' 'bin/${IMG_MAC}' 'bin/${IMG_WINDOWS}'

  - name: build-linux
    env:
      GOOS: linux
      GOARCH: amd64
    run:
      - garble -literals -tiny build --ldflags="-X 'github.com/dcgsteve/secrets/cmd.Version=${BUILD}' -X 'github.com/dcgsteve/secrets/cmd.EncryptionKey=${SECRETS_LIVE_KEY}'" -o bin/${IMG_LINUX}

  - name: build-mac
    env:
      GOOS: darwin
      GOARCH: arm64
    run:
      - garble -literals -tiny build --ldflags="-X 'github.com/dcgsteve/secrets/cmd.Version=${BUILD}' -X 'github.com/dcgsteve/secrets/cmd.EncryptionKey=${SECRETS_LIVE_KEY}'" -o bin/${IMG_MAC}

  - name: build-windows
    env:
      GOOS: windows
      GOARCH: amd64
    run:
      - garble -literals -tiny build --ldflags="-X 'github.com/dcgsteve/secrets/cmd.Version=${BUILD}' -X 'github.com/dcgsteve/secrets/cmd.EncryptionKey=${SECRETS_LIVE_KEY}'" -o bin/${IMG_WINDOWS}

  - name: install-garble
    description: install Garble (used for production releases)
    run:
      - go install mvdan.cc/garble@latest

  - name: install-gh
    description: install GitHub command line (used for production releases)
    run:
      - bash -c ./install-gh.sh